/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_jaquobia_Glfw */

#ifndef _Included_io_github_jaquobia_Glfw
#define _Included_io_github_jaquobia_Glfw
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_jaquobia_Glfw
 * Method:    glfwInit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_io_github_jaquobia_Glfw_glfwInit
  (JNIEnv *, jclass);

/*
 * Class:     io_github_jaquobia_Glfw
 * Method:    glfwTerminate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_github_jaquobia_Glfw_glfwTerminate
  (JNIEnv *, jclass);

/*
 * Class:     io_github_jaquobia_Glfw
 * Method:    glfwGetVersionString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_github_jaquobia_Glfw_glfwGetVersionString
  (JNIEnv *, jclass);

/*
*/
JNIEXPORT jint JNICALL Java_io_github_jaquobia_Glfw_glfwGetPlatform
  (JNIEnv *, jclass);

JNIEXPORT jboolean JNICALL Java_io_github_jaquobia_Glfw_glfwPlatformSupported
  (JNIEnv *, jclass, jint platform);

/*
 * Class:     io_github_jaquobia_Glfw
 * Method:    glfwGetMonitorsJni
 * Signature: ([J)I
 */
JNIEXPORT jint JNICALL Java_io_github_jaquobia_Glfw_glfwGetMonitorsJni
  (JNIEnv *, jclass, jlongArray);

/*
 * Class:     io_github_jaquobia_Glfw
 * Method:    glfwGetPrimaryMonitor
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_github_jaquobia_Glfw_glfwGetPrimaryMonitor
  (JNIEnv *, jclass);

/*
 * Class:     io_github_jaquobia_Glfw
 * Method:    glfwGetMonitorX
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_io_github_jaquobia_Glfw_glfwGetMonitorX
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_github_jaquobia_Glfw
 * Method:    glfwGetMonitorY
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_io_github_jaquobia_Glfw_glfwGetMonitorY
  (JNIEnv *, jclass, jlong);

JNIEXPORT jint JNICALL Java_io_github_jaquobia_Glfw_glfwGetMonitorWorkX
  (JNIEnv *, jclass, jlong);
JNIEXPORT jint JNICALL Java_io_github_jaquobia_Glfw_glfwGetMonitorWorkY
  (JNIEnv *, jclass, jlong);
JNIEXPORT jint JNICALL Java_io_github_jaquobia_Glfw_glfwGetMonitorWorkWidth
  (JNIEnv *, jclass, jlong);
JNIEXPORT jint JNICALL Java_io_github_jaquobia_Glfw_glfwGetMonitorWorkHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_github_jaquobia_Glfw
 * Method:    glfwGetMonitorPhysicalWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_io_github_jaquobia_Glfw_glfwGetMonitorPhysicalWidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_github_jaquobia_Glfw
 * Method:    glfwGetMonitorPhysicalHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_io_github_jaquobia_Glfw_glfwGetMonitorPhysicalHeight
  (JNIEnv *, jclass, jlong);

JNIEXPORT jfloat JNICALL Java_io_github_jaquobia_Glfw_glfwGetMonitorScaleX
  (JNIEnv *, jclass, jlong);
JNIEXPORT jfloat JNICALL Java_io_github_jaquobia_Glfw_glfwGetMonitorScaleY
  (JNIEnv *, jclass, jlong);
/*
 * Class:     io_github_jaquobia_Glfw
 * Method:    glfwGetMonitorName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_github_jaquobia_Glfw_glfwGetMonitorName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_github_jaquobia_Glfw
 * Method:    glfwGetVideoModesJni
 * Signature: (J[I)I
 */
JNIEXPORT jint JNICALL Java_io_github_jaquobia_Glfw_glfwGetVideoModesJni
  (JNIEnv *, jclass, jlong, jintArray);

/*
 * Class:     io_github_jaquobia_Glfw
 * Method:    glfwGetVideoModeJni
 * Signature: (J[I)V
 */
JNIEXPORT void JNICALL Java_io_github_jaquobia_Glfw_glfwGetVideoModeJni
  (JNIEnv *, jclass, jlong, jintArray);

/*
 * Class:     io_github_jaquobia_Glfw
 * Method:    glfwSetGamma
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_io_github_jaquobia_Glfw_glfwSetGamma
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     io_github_jaquobia_Glfw
 * Method:    glfwDefaultWindowHints
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_github_jaquobia_Glfw_glfwDefaultWindowHints
  (JNIEnv *, jclass);

/*
 * Class:     io_github_jaquobia_Glfw
 * Method:    glfwWindowHint
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_io_github_jaquobia_Glfw_glfwWindowHint
  (JNIEnv *, jclass, jint, jint);

JNIEXPORT void JNICALL Java_io_github_jaquobia_Glfw_glfwWindowHintString
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     io_github_jaquobia_Glfw
 * Method:    glfwCreateWindowJni
 * Signature: (IILjava/lang/String;JJ)J
 */
JNIEXPORT jlong JNICALL Java_io_github_jaquobia_Glfw_glfwCreateWindowJni
  (JNIEnv *, jclass, jint, jint, jstring, jlong, jlong);

/*
 * Class:     io_github_jaquobia_Glfw
 * Method:    glfwDestroyWindow
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_github_jaquobia_Glfw_glfwDestroyWindow
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_github_jaquobia_Glfw
 * Method:    glfwWindowShouldClose
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_io_github_jaquobia_Glfw_glfwWindowShouldClose
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_github_jaquobia_Glfw
 * Method:    glfwSetWindowShouldClose
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_io_github_jaquobia_Glfw_glfwSetWindowShouldClose
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     io_github_jaquobia_Glfw
 * Method:    glfwSetWindowTitle
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_github_jaquobia_Glfw_glfwSetWindowTitle
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     io_github_jaquobia_Glfw
 * Method:    glfwSetWindowPos
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_io_github_jaquobia_Glfw_glfwSetWindowPos
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     io_github_jaquobia_Glfw
 * Method:    glfwGetWindowX
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_io_github_jaquobia_Glfw_glfwGetWindowX
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_github_jaquobia_Glfw
 * Method:    glfwGetWindowY
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_io_github_jaquobia_Glfw_glfwGetWindowY
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_github_jaquobia_Glfw
 * Method:    glfwGetWindowWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_io_github_jaquobia_Glfw_glfwGetWindowWidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_github_jaquobia_Glfw
 * Method:    glfwGetWindowHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_io_github_jaquobia_Glfw_glfwGetWindowHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_github_jaquobia_Glfw
 * Method:    glfwSetWindowSize
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_io_github_jaquobia_Glfw_glfwSetWindowSize
  (JNIEnv *, jclass, jlong, jint, jint);


JNIEXPORT void JNICALL Java_io_github_jaquobia_Glfw_glfwSetWindowSizeLimits
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

JNIEXPORT void JNICALL Java_io_github_jaquobia_Glfw_glfwSetWindowAspectRatio
  (JNIEnv *, jclass, jlong, jint, jint);

JNIEXPORT jfloat JNICALL Java_io_github_jaquobia_Glfw_glfwGetWindowOpacity
  (JNIEnv *, jclass, jlong);

JNIEXPORT void JNICALL Java_io_github_jaquobia_Glfw_glfwSetWindowOpacity
  (JNIEnv *, jclass, jlong, jfloat);


/*
 * Class:     io_github_jaquobia_Glfw
 * Method:    glfwIconifyWindow
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_github_jaquobia_Glfw_glfwIconifyWindow
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_github_jaquobia_Glfw
 * Method:    glfwRestoreWindow
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_github_jaquobia_Glfw_glfwRestoreWindow
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_github_jaquobia_Glfw
 * Method:    glfwHideWindow
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_github_jaquobia_Glfw_glfwHideWindow
  (JNIEnv *, jclass, jlong);

JNIEXPORT void JNICALL Java_io_github_jaquobia_Glfw_glfwMaximizeWindow
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_github_jaquobia_Glfw
 * Method:    glfwShowWindow
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_github_jaquobia_Glfw_glfwShowWindow
  (JNIEnv *, jclass, jlong);

JNIEXPORT void JNICALL Java_io_github_jaquobia_Glfw_glfwFocusWindow
  (JNIEnv *, jclass, jlong);

JNIEXPORT void JNICALL Java_io_github_jaquobia_Glfw_glfwRequestWindowAttention
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_github_jaquobia_Glfw
 * Method:    glfwGetWindowMonitor
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_github_jaquobia_Glfw_glfwGetWindowMonitor
  (JNIEnv *, jclass, jlong);
JNIEXPORT jlong JNICALL Java_io_github_jaquobia_Glfw_glfwGetCurrentWindowMonitor
  (JNIEnv *, jclass, jlong);
JNIEXPORT void JNICALL Java_io_github_jaquobia_Glfw_glfwSetCurrentWindowMonitor
  (JNIEnv *, jclass, jlong);

JNIEXPORT void JNICALL Java_io_github_jaquobia_Glfw_glfwSetWindowMonitor
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jint, jint, jint);
JNIEXPORT void JNICALL Java_io_github_jaquobia_Glfw_glfwSetWindowMonitorDefault
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_github_jaquobia_Glfw
 * Method:    glfwGetWindowAttrib
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_io_github_jaquobia_Glfw_glfwGetWindowAttrib
  (JNIEnv *, jclass, jlong, jint);

JNIEXPORT void JNICALL Java_io_github_jaquobia_Glfw_glfwSetWindowAttrib
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     io_github_jaquobia_Glfw
 * Method:    glfwSetCallbackJni
 * Signature: (Lio/github/jaquobia/GlfwCallback;)V
 */
JNIEXPORT void JNICALL Java_io_github_jaquobia_Glfw_glfwSetCallbackJni
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_github_jaquobia_Glfw
 * Method:    glfwPollEventsJni
 * Signature: (Lio/github/jaquobia/GlfwCallback;)V
 */
JNIEXPORT void JNICALL Java_io_github_jaquobia_Glfw_glfwPollEventsJni
  (JNIEnv *, jclass, jobject);

/*
 * Class:     io_github_jaquobia_Glfw
 * Method:    glfwWaitEventsJni
 * Signature: (Lio/github/jaquobia/GlfwCallback;)V
 */
JNIEXPORT void JNICALL Java_io_github_jaquobia_Glfw_glfwWaitEventsJni
  (JNIEnv *, jclass, jobject);

JNIEXPORT void JNICALL Java_io_github_jaquobia_Glfw_glfwWaitEventsTimeoutJni
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     io_github_jaquobia_Glfw
 * Method:    glfwGetInputMode
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_io_github_jaquobia_Glfw_glfwGetInputMode
  (JNIEnv *, jclass, jlong, jint);

JNIEXPORT jstring JNICALL Java_io_github_jaquobia_Glfw_glfwGetKeyName
  (JNIEnv *, jclass, jint, jint);
JNIEXPORT jint JNICALL Java_io_github_jaquobia_Glfw_glfwGetScancode
  (JNIEnv *, jclass, jint);

/*
 * Class:     io_github_jaquobia_Glfw
 * Method:    glfwSetInputMode
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_io_github_jaquobia_Glfw_glfwSetInputMode
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     io_github_jaquobia_Glfw
 * Method:    glfwGetKey
 * Signature: (JI)Z
 */
JNIEXPORT jint JNICALL Java_io_github_jaquobia_Glfw_glfwGetKey
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     io_github_jaquobia_Glfw
 * Method:    glfwGetMouseButton
 * Signature: (JI)Z
 */
JNIEXPORT jint JNICALL Java_io_github_jaquobia_Glfw_glfwGetMouseButton
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     io_github_jaquobia_Glfw
 * Method:    glfwGetCursorPosX
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_io_github_jaquobia_Glfw_glfwGetCursorPosX
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_github_jaquobia_Glfw
 * Method:    glfwGetCursorPosY
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_io_github_jaquobia_Glfw_glfwGetCursorPosY
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_github_jaquobia_Glfw
 * Method:    glfwSetCursorPos
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_io_github_jaquobia_Glfw_glfwSetCursorPos
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     io_github_jaquobia_Glfw
 * Method:    glfwGetJoystickParam
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_io_github_jaquobia_Glfw_glfwGetJoystickParam
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     io_github_jaquobia_Glfw
 * Method:    glfwGetJoystickAxes
 * Signature: (I[F)I
 */
JNIEXPORT jint JNICALL Java_io_github_jaquobia_Glfw_glfwGetJoystickAxes
  (JNIEnv *, jclass, jint, jfloatArray);

/*
 * Class:     io_github_jaquobia_Glfw
 * Method:    glfwGetJoystickButtons
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_io_github_jaquobia_Glfw_glfwGetJoystickButtons
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     io_github_jaquobia_Glfw
 * Method:    glfwGetJoystickName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_github_jaquobia_Glfw_glfwGetJoystickName
  (JNIEnv *, jclass, jint);

/*
 * Class:     io_github_jaquobia_Glfw
 * Method:    glfwSetClipboardString
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_github_jaquobia_Glfw_glfwSetClipboardString
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     io_github_jaquobia_Glfw
 * Method:    glfwGetClipboardString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_github_jaquobia_Glfw_glfwGetClipboardString
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_github_jaquobia_Glfw
 * Method:    glfwGetTime
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_io_github_jaquobia_Glfw_glfwGetTime
  (JNIEnv *, jclass);

/*
 * Class:     io_github_jaquobia_Glfw
 * Method:    glfwSetTime
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_io_github_jaquobia_Glfw_glfwSetTime
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     io_github_jaquobia_Glfw
 * Method:    glfwMakeContextCurrentJni
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_github_jaquobia_Glfw_glfwMakeContextCurrentJni
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_github_jaquobia_Glfw
 * Method:    glfwGetCurrentContext
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_github_jaquobia_Glfw_glfwGetCurrentContext
  (JNIEnv *, jclass);

/*
 * Class:     io_github_jaquobia_Glfw
 * Method:    glfwSwapBuffers
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_github_jaquobia_Glfw_glfwSwapBuffers
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_github_jaquobia_Glfw
 * Method:    glfwSwapInterval
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_io_github_jaquobia_Glfw_glfwSwapInterval
  (JNIEnv *, jclass, jint);

/*
 * Class:     io_github_jaquobia_Glfw
 * Method:    glfwExtensionSupported
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_github_jaquobia_Glfw_glfwExtensionSupported
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
